-- Add all missing site_settings columns
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS site_name TEXT DEFAULT 'SuperShop',
  ADD COLUMN IF NOT EXISTS site_description TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS site_title TEXT DEFAULT 'SuperShop - Modern E-Commerce',
  ADD COLUMN IF NOT EXISTS logo_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS favicon_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#3B82F6',
  ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#1E40AF',
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'OMR',
  ADD COLUMN IF NOT EXISTS currency_symbol TEXT DEFAULT '$',
  ADD COLUMN IF NOT EXISTS support_email TEXT DEFAULT 'support@supershop.com',
  ADD COLUMN IF NOT EXISTS support_phone TEXT DEFAULT '+1 (555) 123-4567',
  ADD COLUMN IF NOT EXISTS contact_email TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_phone TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS contact_address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS working_hours TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_description TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_copyright TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_tagline TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS footer_text TEXT DEFAULT '© 2026 SuperShop. All rights reserved.',
  ADD COLUMN IF NOT EXISTS whatsapp_number TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram_handle TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS free_shipping_threshold NUMERIC(10,2) DEFAULT 30,
  ADD COLUMN IF NOT EXISTS facebook_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS twitter_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube_url TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS facebook_pixel_id TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS facebook_pixel_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS facebook_capi_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS facebook_access_token TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS facebook_test_event_code TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS facebook_api_version TEXT DEFAULT 'v21.0',
  ADD COLUMN IF NOT EXISTS tiktok_pixel_id TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiktok_pixel_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS tiktok_access_token TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS google_analytics_id TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS google_tag_manager_id TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tracking_pageview BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS tracking_viewcontent BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS tracking_addtocart BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS tracking_initiatecheckout BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS tracking_purchase BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS tracking_lead BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS tracking_complete_registration BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS default_content_type TEXT DEFAULT 'product',
  ADD COLUMN IF NOT EXISTS test_event_code TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_title TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_description TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS meta_keywords TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en';
